export enum JsonTaskType {
	continuePrint = 'continuePrint',
	openShift = 'openShift',
	closeShift = 'closeShift',
	sell = 'sell',
	buy = 'buy',
	sellReturn = 'sellReturn',
	buyReturn = 'buyReturn',
	sellCorrection = 'sellCorrection',
	buyCorrection = 'buyCorrection',
	sellReturnCorrection = 'sellReturnCorrection',
	buyReturnCorrection = 'buyReturnCorrection',
	nonFiscal = 'nonFiscal',
	reportX = 'reportX',
	cashIn = 'cashIn',
	cashOut = 'cashOut',
	reportOfdExchangeStatus = 'reportOfdExchangeStatus',
	printFnDocument = 'printFnDocument',
	printLastReceiptCopy = 'printLastReceiptCopy',
	getRegistrationInfo = 'getRegistrationInfo',
	registration = 'registration',
	fnChange = 'fnChange',
	changeRegistrationParameters = 'changeRegistrationParameters',
	closeArchive = 'closeArchive',
	openCashDrawer = 'openCashDrawer',
	setDateTime = 'setDateTime',
	getDeviceParameters = 'getDeviceParameters',
	setDeviceParameters = 'setDeviceParameters',
	getDeviceInfo = 'getDeviceInfo',
	getMcu = 'getMcu',
	getDeviceStatus = 'getDeviceStatus',
	getCashDrawerStatus = 'getCashDrawerStatus',
	getShiftStatus = 'getShiftStatus',
	getFnInfo = 'getFnInfo',
	getFnStatus = 'getFnStatus',
	ofdExchangeStatus = 'ofdExchangeStatus',
	getShiftTotals = 'getShiftTotals',
	getOverallTotals = 'getOverallTotals',
	getDepartmentSum = 'getDepartmentSum',
	getFnDocument = 'getFnDocument',
	getLicenses = 'getLicenses',
	reportDepartments = 'reportDepartments',
	reportFnRegistrations = 'reportFnRegistrations',
	printDocumentsFromJournal = 'printDocumentsFromJournal',
	ismExchangeStatus = 'ismExchangeStatus',
	beginMarkingCodeValidation = 'beginMarkingCodeValidation',
	getMarkingCodeValidationStatus = 'getMarkingCodeValidationStatus',
	acceptMarkingCode = 'acceptMarkingCode',
	declineMarkingCode = 'declineMarkingCode',
	cancelMarkingCodeValidation = 'cancelMarkingCodeValidation',
	clearMarkingCodeValidationResult = 'clearMarkingCodeValidationResult',
	checkMarkingCodeValidationsReady = 'checkMarkingCodeValidationsReady',
	validateMarks = 'validateMarks',
	addMarksToBuffer = 'addMarksToBuffer',
	checkImcWorkState = 'checkImcWorkState',
	checkImcTime = 'checkImcTime',
	pingIsm = 'pingIsm',
}

export function isJsonTaskType(v: unknown): v is JsonTaskType {
	return Object.values(JsonTaskType).includes((v as JsonTaskType));
}
